tests: Cleanup decompiler test fixtures and try to improve the test output / add a readable report (#1724)
* tests: add a Jak2 `FormRegressionTest` fixture

* tests/ci: minimize test log output and produce a readable report

* improve naming of report due to underlying GitHub issue

* hopefully fix windows handling of this argument

* test...

* final test

* test linux coverage

diff --git a/.github/workflows/linux-build-clang.yaml b/.github/workflows/linux-build-clang.yaml
--- a/.github/workflows/linux-build-clang.yaml
+++ b/.github/workflows/linux-build-clang.yaml
@@ -52,7 +52,17 @@ jobs:
         run: cmake --build build -j$((`nproc`+1))
 
       - name: Run Tests
+        env:
+          GTEST_OUTPUT: "xml:opengoal-test-report.xml"
         run: ./test.sh
+
+      - name: Generate Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Linux Clang - Test Report
+          path: ${{ github.workspace }}/**/opengoal-test-report.xml
+          reporter: jest-junit
 
       - name: Upload artifact
         uses: actions/upload-artifact@v3
diff --git a/.github/workflows/windows-build-msvc.yaml b/.github/workflows/windows-build-msvc.yaml
--- a/.github/workflows/windows-build-msvc.yaml
+++ b/.github/workflows/windows-build-msvc.yaml
@@ -49,4 +49,15 @@ jobs:
 
       - name: Run Tests
         timeout-minutes: 10
-        run: ./build/bin/goalc-test.exe --gtest_color=yes --gtest_filter="-*MANUAL_TEST*"
+        env:
+          GTEST_OUTPUT: "xml:opengoal-test-report.xml"
+        run: |
+          ./build/bin/goalc-test.exe --gtest_color=yes --gtest_brief=1 --gtest_filter="-*MANUAL_TEST*"
+
+      - name: Generate Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Windows MSVC - Test Report
+          path: ./opengoal-test-report.xml
+          reporter: jest-junit
