tests/ci: minimize test log output and produce a readable report

diff --git a/.github/workflows/windows-build-clang.yaml b/.github/workflows/windows-build-clang.yaml
--- a/.github/workflows/windows-build-clang.yaml
+++ b/.github/workflows/windows-build-clang.yaml
@@ -48,7 +48,17 @@ jobs:
 
       - name: Run Tests
         timeout-minutes: 10
-        run: ./build/bin/goalc-test.exe --gtest_color=yes --gtest_filter="-*MANUAL_TEST*"
+        env:
+          GTEST_OUTPUT: "xml:${{ github.workspace }}/test-report.xml"
+        run: ./build/bin/goalc-test.exe --gtest_color=yes --gtest_brief=1 --gtest_filter="-*MANUAL_TEST*"
+
+      - name: Generate Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Unit Tests
+          path: ${{ github.workspace }}/test-report.xml
+          reporter: jest-junit
 
       - name: Upload artifact
         uses: actions/upload-artifact@v3
